@startuml Activity

!pragma layout smetana
!theme plain

legend top left
    <b>2. Activity Diagram
    ----
    <b>Запуск отчетов
    ----
    Version: 0.2
    Date: 16/09/25
    -- Обозначения --
    <b>&&</b> — обязательно соблюдение всех условий
end legend

|Сотрудник|
start
    :Выбирает конфигурацию отчета;
    :Инициирует апуск отчёта;

|Приложение|
    if (Конфигурация корректна? (необходимые поля заполнены, параметры валидны) \n<b>&& \nОтчет остановлен?) then (Да)
    else (Нет)
        :Отображает сообщение об ошибке сотруднику;
        :Делает запись в лог;
        stop
    endif


    if (Yandex Direct API доступен) then (Да)
        :Инициирует \n<b>сбор данных через Yandex Direct API;
    else (Нет)
        :Отображает сообщение об ошибке сотруднику;
        :Делает запись в лог;
        stop
    endif

    :Обновляет статус конфигурации отчета на "Активен";
    :Отображает сообщение об успехе сотруднику;

stop

@enduml