@startuml Activity

!pragma layout smetana
!theme plain

legend top left
    <b>2. Activity Diagram
    ----
    <b>Удаление пользователя
    ----
    Version: 0.1
    Date: 22/09/25
end legend


|Администратор|
start
    :Инициировать удаление \nпользователя;

|Система|

    if (Удаляемый пользователь — \nпоследний администратор) then (Нет)
    :Удалить пользователя;
    :Обновить список \nпользователей;
    :Сделать запись в лог;
    :Вывести сообщение \nоб успешном удалении;
    else (Да)
    :Вывести сообщение \nоб ошибке;
    :Сделать запись в лог;
    endif

|Администратор|
    :Вернуться к списку \nпользователей;

stop
@enduml