@startuml Activity

!pragma layout smetana
!theme plain

legend top left
    <b>2. Activity Diagram
    ----
    <b>Удаление конфигурации отчета
    ----
    Version: 0.2
    Date: 16/09/25
end legend

|Сотрудник|
start
    :Выбирает конфигурацию;
    :Инициирует удаление конфигурации;

|Система|
    :Спрашивает подтверждение удаления;

|Сотрудник|
    if (Подтверждает удаление) then (Да)
    else (Нет)
        :Отмена операции;
        stop
    endif

|Система|
    if (Проверяет существование \nконфигурации отчетов) then (Существует)
    else (Не существует)
        :Показывает сообщение об ошибке;
        :Делает запись в лог;
        stop
    endif

    if (Проверяет наличие запущенных отчетов) then (Запущенных \nотчетов нет)
    else (Запущенные \nотчеты есть)
        :Показывает предупреждение \nо запущенных отчетах;
        :Спрашивает об остановке \nзапущенных отчетов;
|Сотрудник|
        if (Подтверждает остановку) then (Да)
        else (Нет)
            :Отмена операции;
            stop
        endif
    endif
|Система|
    :Удаляет конфигурацию отчетов;
    :Обновляет список конфигураций отчетов;
    :Показывает сообщение об успешном удалении;

stop

@enduml