@startuml Activity

!pragma layout smetana
!theme plain

legend top left
    <b>2. Activity Diagram
    ----
    <b>Удаление пользователя
    ----
    Version: 0.1
    Date: 22/09/25
end legend


|Администратор|
start
:Инициировать \nизменение частоты;
repeat
|Система|
:Предоставить поле \nдля изменения частоты;

|Администратор|
:Ввести новую частоту \n(ч/сбор);
:Подтвердить введенную частоту;

|Система|
backward :Показать сообщение \nоб ошибке ввода;
repeat while (частота меньше одной проверки в <b>1</b> час) is (Да);
:;


stop
@enduml