@startuml

left to right direction

'!pragma layout smetana
skinparam linetype ortho
'skinparam linetype polyline

    legend top left
        <b>3. Class.</b> Имплементационная перспектива
        ----
        Version: 0.2.2
        Date: 02/12/25
    '    -- Автор --
    '    Pavel Isaenko
        -- Обозначения --
        — Бизнес-логика и сущности обозначены в разделе "Business"
        — JpaRepository обозначены для удобства. Они уже определены в Spring JPA
    end legend

rectangle "Business" {
    entity User {
            - String name
            - String login
            - Role role
            - String passwordHash
            - LocalDateTime createdAt
            - LocalDateTime changedAt

            + void updateChangingDate()
    }

    record Goal {
        - String goalName
        - Integer goalValue
    }

    enum Role {
        - String name
        - String description
    }

    class CampaignToReportTemplate {
        - Long id
        - Campaign campaign
        - ReportTemplate reportTemplate
    }

    entity ReportTemplate {
        - String name
        - Set<CampaignToReportTemplate> reportTemplatesSet
        - Client client
        - List<Report> reportsList
        - int frequency
        - User createdBy
        - ZonedDateTime createdAt
        - User changedBy
        - ZonedDateTime changedAt
        - boolean isActive
        - String dashboardURL

        + void updateName(String newName)
        + void addCampaign(Campaign newCampaign)
        + void deleteCampaign(Campaign campaign)
        + void activate()
        + void deactivate()
    }
    note right of ReportTemplate::frequency
        Нужна Quartz-реализация
    end note
    entity Report {
        - ReportTemplate reportTemplate
        - int impressions
        - int clicks
        - int ctr
        - int avgClickPrice
        - int cancels
        - int conversionPrice
        - int conversionCoef
        - List<Goal> goals
        - ZonedDateTime createdAt
    }

    entity Client {
        - String name
        - String yaDirectLogin
        - List<Campaign> campaignsList
    }

    entity Campaign {
        - String name
        - Client client
        - String deviceType
        - String platform
        - Set<CampaignToReportTemplate> campaignsSet
    }
}

rectangle "Users"{
    interface JpaRepository<User, Integer> <<external>>
    interface UserRepository extends JpaRepository<User, Integer>{
    }

    JpaRepository ..> User
    UserService --> UserRepository
    UserService ..> User

    class UserService{
        - UserRepository userRepository

        + List<User> getAllUsers()
        + User getUserById()
        + void createUser(String name, String login, String role, String password)
        + void updateUser(String newName, String login, String role, String password)
        + void deleteUser(User user)
    }
}

rectangle "Campaigns" {
    interface JpaRepository<Campaign, Integer> <<external>>
    interface CampaignRepository extends JpaRepository<Campaign, Integer> {

    }
    JpaRepository ..> Campaign
    CampaignService --> CampaignRepository

    class CampaignService {
        - CampaignRepository campaignRepository
        + getAllCampaigns()
        + getCampaignsByClient()
    }
}

rectangle "Reports" {
    interface JpaRepository<Report, Integer> <<external>>
    interface ReportRepository extends JpaRepository<Report, Integer> {
    }
    JpaRepository ..> Report
    ReportService --> ReportRepository

    class ReportService {

    }
}

rectangle "ReportTemplates" {
    interface JpaRepository<ReportTemplate, Integer> <<external>>
    interface ReportTemplateRepository extends JpaRepository<ReportTemplate, Integer>{
    }
    JpaRepository ..> ReportTemplate
    ReportTemplateService --> ReportTemplateRepository

    class ReportTemplateService {
        - ReportTemplateRepository reportTemplateRepository
        + void createReportTemplate(String name, Client client, List<Campaign> campaignsList)
        + void deleteReportTemplate(ReportTemplate reportTemplate)
        + List<ReportTemplate> getAllReportTemplates()
        + ReportTemplate getReportTemplate(ReportTemplate reportTemplate)
        + void startReportTemplate(ReportTemplate reportTemplate)
        + void stopReportTemplate(ReportTemplate reportTemplate)
    }
}

rectangle "Clients" {
    interface JpaRepository<Client, Integer> <<external>>
    interface ClientRepository extends JpaRepository<Client, Integer> {
    }
    JpaRepository ..> Client
    ClientService --> ClientRepository

    class ClientService {
    }
}

rectangle "CampaignsToReportTemplates" {
    interface JpaRepository<CampaignsToReportTemplate, Integer> <<external>>
    interface CampaignToReportTemplateRepository implements JpaRepository<CampaignToReportTemplate, Integer> {
        findByReportTemplate(ReportTemplate reportTemplate)
        findByCampaign(Campaign campaign)
        deleteByReportTemplate(ReportTemplate reportTemplate)
    }
    JpaRepository ..> CampaignToReportTemplate
    CampaignToReportTemplateService --> CampaignToReportTemplateRepository

    class CampaignToReportTemplateService {
    }
}
'
'class MainPageController {
'    - UserService
'
'    + addUserToModel()
'    + showPage()
'}



class ReportTemplatesController {
    - ReportTemplateService
    - UserService userService
    + String showPage()
}

class ReportTemplateController {
    - ReportTemplateService reportTemplateService
    - UserService userService
    + String showPage()
    + void deleteReportTemplateProcess()
    + void startReportTemplate()
    + void stopReportTemplate()
}

class ReportTemplateCreationPageController {
    - UserService userService
    - ReportTemplateService reportTemplateService
    - CampaignService campaignService
    - ClientService clientService
    + void createReportTemplateProcess()
}

class ClientsController {
    - UserService userService
    - ClientService clientService
    + String showPage()
}

class ClientController {
    - UserService userService
    - ClientService clientService
    + String showPage()
}

class UserRegistrationPageController {
    - UserService userService
    + String showPage()
    + registrationProcess()
}

class UserController {
    - UserService userService
    + String showPage()
    + void deleteUserProcess()
}

class UserUpdatePageController {
    - UserService userService
    + String showPage()
    + void updateUserProcess()
}

class UsersController {
    - UserService userService
    + void addUserToModel(Model)
    + String showPage()
}

User "*" --> "1" Role : role
ReportTemplate "*" --> "1" User : createdBy
ReportTemplate "*" --> "1" User : changedBy
'ReportTemplate "*" -- "*" Campaign
ReportTemplate "1" -- "*" CampaignToReportTemplate : reportTemplatesSet
CampaignToReportTemplate "*" -- "1" Campaign : campaignsSet
ReportTemplate "*" -- "1" Client : client
ReportTemplate "1" -- "*" Report : reportTemplate
Client "1" -- "*" Campaign : client
Report "1" -- "*" Goal : goals


UsersController --> UserService

UserController --> UserService

ClientsController --> UserService
ClientsController --> ClientService

ClientController --> UserService
ClientController --> ClientService

UserRegistrationPageController --> UserService

UserUpdatePageController --> UserService

ReportTemplatesController --> ReportTemplateService
ReportTemplatesController --> UserService

ReportTemplateController --> ReportTemplateService
ReportTemplateController --> UserService

ReportTemplateCreationPageController --> UserService
ReportTemplateCreationPageController --> ReportTemplateService
ReportTemplateCreationPageController --> CampaignService
ReportTemplateCreationPageController --> ClientService

'MainPageController --> UserService

@enduml







