@startuml Activity

!pragma layout smetana
!theme plain

legend top left
    <b>2. Activity Diagram
    ----
    <b>Добавление нового пользователя
    ----
    Version: 0.1
    Date: 16/09/25
    -- Обозначения --
    <b>||</b> — Хотя бы одно из условий выполняется
    .../<b>сотрудник</b>] — роль по-умолчанию
end legend


|Администратор|
start
    :Инициировать создание пользователя;
    repeat

        fork
            :Ввести ФИО пользователя;
        fork again
            :Ввести логин;
        fork again
        'Подумать над отправкой пароля на email
            :Ввести пароль;
            :Подтвердить пароль;
        fork again
            :Выбрать роль
            [администратор/<b>сотрудник</b>];
        end fork

|Система|
    backward :Показать сообщения \nоб ошибках возле некорректных полей;

    repeat while (ФИО отсутствует \n<b>||</b> \nЛогин уже существует \n<b>||</b> \nПароль не соответствует требованиям) is (Да)

    :Обновить список пользователей;

stop
@enduml