@startuml Activity

!pragma layout smetana
!theme plain

legend top left
    <b>2. Activity Diagram
    ----
    <b>Остановка отчетов
    ----
    Version: 0.2
    Date: 16/09/25
end legend

|Сотрудник|
start
    :Выбирает конфигурацию отчета;
    :Нажимает "Остановить отчёт";

|Приложение|
    if (Отчет запущен?) then (Да)
        :Инициирует \n<b>остановку сбора данных через Yandex Direct API;
        :Обновляет статус конфигурации отчета на "Не активен";
        :Отображает сообщение об успехе сотруднику;
    else (Нет)
        :Отображает сообщение об ошибке сотруднику;
        :Делает запись в лог;
    endif

stop

@enduml