@startuml Activity

!pragma layout smetana
!theme plain

legend top left
    <b>2. Activity Diagram
    ----
    <b>Изменение данных пользователя
    ----
    Version: 0.1
    Date: 16/09/25
    -- Обозначения --
    <b>||</b> — Хотя бы одно из условий выполняется
end legend

|Администратор|
start

:Выбрать пользователя;
:Инициировать изменение полей \nвыбранного пользователя;

|Система|
:Предоставить поля для изменения;

|Администратор|
repeat
:Внести изменения;

|Система|
backward :Показать сообщение \nо некорректных данных;
repeat while (ФИО отсутствует \n<b>||</b> \nЛогин уже существует \n<b>||</b> \nПароль не соответствует требованиям) is (Да)

:Обновить данные пользователя;
:Показать сообщение об \nуспешном изменении данных;

stop
@enduml