@startuml Activity

!pragma layout smetana
!theme plain

legend top left
    <b>2. Activity Diagram
    ----
    <b>Сбор данных по расписанию
    ----
    Version: 0.2
    Date: 22/09/25
end legend

|Система|
start
    :Сработал таймер расписания;
    :Инициировать процесс сбора данных;

|Яндекс Директ API|
    :Предоставить данные;

|Система|
    if (Данные получены успешно?) then (Да)
        :Сохранить данные в БД;
        :Сделать запись в лог;
    else (Нет)
        :Сделать запись об ошибке в лог;
    endif

stop
@enduml