@startuml Activity

!pragma layout smetana
!theme plain

legend top left
    <b>2. Activity Diagram
    ----
    <b>Предоставление данных для дашборда
    ----
    Version: 0.1
    Date: 23/09/25
    -- Обозначения --
    PgSQL — Postgres SQL
end legend

|Пользователь|
start
    :Открыть дашборд;

|Datalens|
    :Войти в PgSQL;
    :Запросить данные для обработки у PgSQL;

|Система (PgSQL)|
    :Получить запрос на данные;
    :Извлечь данные из хранилища;

    :Вернуть совпадающие строки;
    note
    если совпадений нет,
    возвращается пустой результат
    end note

|Datalens|
    :Обработать полученные данные;
    :Показать готовый дашборд пользователю;

|Пользователь|
    :Просмотреть данные на дашборде;

stop
@enduml
